---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        ver: 1.5.3
        meta: ent
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        ver: 1.5.3
        meta: ent.hsm
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
