---
- name: Test andrewrothstein.vault for ent
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        meta: ent
- name: Test andrewrothstein.vault for ent.hsm
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        meta: ent.hsm
- name: Test andrewrothstein.vault standard
  hosts: all
  tasks:
    - name: Installing andrewrothstein.vault
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'vault --version'
      ansible.builtin.command: /usr/local/bin/vault --version
      changed_when: false
      register: vault_test_output
    - name: Output of 'vault --version'
      ansible.builtin.debug:
        msg: '{{ vault_test_output.stdout }}'
