---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        meta: ent
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      vault_app:
        name: vault
        meta: ent.hsm
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/vault --version
      register: vault_test_output
    - debug:
        msg: '{{ vault_test_output.stdout }}'
