---
- name: Installing vault binaries
  ansible.builtin.include_role:
    name: andrewrothstein.hashi
  vars:
    hashi_apps:
      - name: '{{ vault_app.name | default("vault") }}'
        ver: '{{ vault_app.ver | default(vault_ver) }}'
        meta: '{{ vault_app.meta | default("") }}'
